### ISSUE TITLE
Test: 그룹 멤버 기능 테스트 코드 와 api 명세 작성

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/backend#19]
# TODO
- [ ] 플래너 리스트 반환 테스트 코드 작성 -> 명세 제외
  - 그룹멤버 isLeaved 의 값에 따른 적절한 리스트 반환 여부 확인이 목적
 - [ ] 그룹멤버 기능 테스트 코드 작성
   - 그룹멤버 검색 기능
   - 그룹멤버 추가 기능
   - 그룹멤버 삭제 기능
   - 그룹멤버 리스트 반환 기능
 - [ ] api 명세 작성
