### ISSUE TITLE
Test: 실시간 채팅 기능 테스트 코드와 api 명세 작성

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/backend#23]
# TODO
- [x] 실시간 채팅 기능 테스트 코드 작성
- [x] 실시간 채팅 기능 api 명세 작성
- [x] 그룹멤버 확인 기능 명세에 추가 -> #19
