### ISSUE TITLE
Feat: 유저 기능 구현

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/backend#3]
# 구현 기능
- 로그인 / 회원가입 기능을 구현합니다.
- 소셜 로그인은 차후에 추가 예정이라 P&R 이후에도 Issue 를 닫지 않습니다.
  - 브랜치는 삭제 합니다.

<br>

# TODO
- [x] @sieunnnn security 설정
- [x] @sieunnnn 각종 util 설정
- [x] @sieunnnn 가이드라인 작성
- [x] @chwmyway97 user entity 작성
- [x] @chwmyway97 회원 가입 기능 구현
- [x] @chwmyway97 로그인 기능 구현
- [x] @sieunnnn 테스트 코드 작성 / 수행
- [x] @sieunnnn api 명세 작성
- [x] @sieunnnn deploy, front 에게 업데이트 사항 알리기

**Comment by sieunnnn** [comment]
# 추가 구현 기능
- 로그인 이후 유저 정보 반환
- 회원가입 시 진행 될 이메일 인증 절차

<br>

# TODO
- [x] @sieunnnn 유저정보 반환 가이드라인 작성
- [x] @chwmyway97 유저정보 반환 기능 구현
- [x] @sieunnnn 비밀번호, 닉네임 등 validation 추가
- [x] @sieunnnn 로그아웃 기능 구현
- [ ] @sieunnnn 이메일 인증 기능 구현
- [x] @sieunnnn 두 기능 테스트 코드 생성
- [x] @sieunnnn api 명세 작성

**Comment by sieunnnn** [comment]
# 유저 회원 탈퇴 여부를 boolean 으로 표기함에 따른 변경점
✅ 유저 회원 탈퇴 기능 관련 이슈 (https://github.com/planner-project/backend/issues/4)

<br>

# TODO
- [x] @sieunnnn 회원가입 시 프로필 이미지 같이 저장
- [x] @sieunnnn 로그인 시 유저의 isWithdrawal 이 false 일 경우에만 로그인이 가능해야 합니다.
  - 이메일과 비밀번호가 알맞지만 isWithdrawal 이 true 인 경우 회원 탈퇴한 유저이므로 로그인이 진행되면 안됩니다. 🙅‍♀️
- [x] @chwmyway97 유저 정보 반환 시 프로필 이미지도 같이 반환
