### ISSUE TITLE
Fix: 프론트 요구 사항 반영

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/backend#33]
# TODO
- [x] 유저 엔티티에 성별 필드 추가 -> 관련된 코드 전부 수정
- [x] 플래너 리스트 반환 시 그룹 이미지 세개 반환
- [x] 그룹 멤버 CRUD websocket -> http 로 변경

**Comment by sieunnnn** [comment]
# TODO
- [x] 유저 정보 반환 시 이메일 반환 추가
