### ISSUE TITLE
Fix: 프론트 요구사항 과 버그 처리 

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/backend#35]
# TODO
- [x] 매핑 변경
- [x] 플래너 제목 글자수 제한
- [x] 그룹 멤버 초대 수 제한
- [x] dto 전부 record 로 변경
- [x] planBox isPrivate 필드 관련 내용 삭제
- [x] planBox data `null` 처리
- [x] planner API 명세 추가
