### ISSUE TITLE
Feat: 유저 정보 수정 기능

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/backend#4]
# 구현 기능
- 유저 정보를 수정 합니다.
  - 프로필 이미지
  - 닉네임
  - 비밀번호
- 회원 가입 탈퇴 기능을 구현합니다.

* 이때 delete 를 실제로 하는 것이 아닌 값을 0 으로 변경합니다.

<br>

# TODO
- [x] @sieunnnn 가이드 라인 작성
- [x] @sieunnnn 유저 정보 수정
- [x] @sieunnnn  회원 가입 탈퇴 기능 구현

**Comment by sieunnnn** [comment]
# 변경점
## ERD
ERD 일부분이 변경되었습니다.

## Code
- User Entity 에 Profile 과 관련된 mapping 이 추가 되었습니다.
- User Entity 에 update methods 가 추가 되었습니다.
- Image 관련 util class 가 추가 되었습니다.
- 유저 정보와 프로필 이미지를 수정하는 기능이 추가 되었습니다.
- 유저를 찾는 컴포넌트가 추가 되었습니다.
